version: "3"
 
services:
  jenkins:
    user: root
    image: "jenkinsci/blueocean:latest"
    ports:
      - "8090:8080"
    volumes:
      - ./jenkins_home:/var/jenkins_home
      #- /usr/local/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - mynet
    
networks:
  mynet:
    driver: bridge
