version: '2'

services:
  jenkins:
    image: docker.io/bitnami/jenkins:2
    ports:
      - '90:8080'
    environment:
      - JENKINS_PASSWORD=A1s2d3f4g5.
    volumes:
      - 'jenkins_data:/bitnami/jenkins'

volumes:
  jenkins_data:
    driver: local
